### ISSUE TITLE
store: reconsider design (go type vs json mode)

### ISSUE THREAD

**Issue by jsign** [textileio/go-threads#131]
The added JSONMode has *felt* that some duplication was added in the store code.

The duplication was somewhat necessary since the same logic should have different implementations due to different types being around (reflect mode vs string mode).

I have the feeling that an ideal state of the implementation is leaving the JSON mode to be the only one, and the Go Typed one a wrapper. Despite this sounds good, JSON mode has some limitations regarding possible types of instance attributes (since Go types are more expressive than JSON). The most obvious case is ints and floats. In Go Type mode you can distinguish these two types for queries, but in JSON mode you can't. 

Making the Go Type mode a thin wrapper of JSONMode to avoid duplication would mean adding these limitations to Go Type mode. Also, I don't have quite clear yet the performance implication of both modes... but that should be considered to (eventually benchmark it). On the other hand, doing it this way will wipe out all reflect code which is nice to our eyes.

If we convince ourselves that the real store should be JSONMode (and Go Type a wrapper), then I think I'd reconsider if some JSON library can give optimized and more capabilities to json handling (like path traversing, i.e: _gson_ library) and more importantly the query engine.

**Comment by sanderpick** [comment]
Nice summary. The gjson result type handling (https://github.com/tidwall/gjson#result-type) could serve as some motivation, letting the user pull out the correct type, e.g., int vs. float. Though, these limitations may have deeper consequences at the db level, i.e., having to store all numbers as `float64`.

**Comment by asutula** [comment]
For now, just making json mode the only mode.
