### ISSUE TITLE
Check that a store has been 'started' before attempting to access it

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-threads#167]
Currently, if you haven't called `start` or `startFromAddress` from the gRPC client, the gRPC server will panic. This is a pretty simple check, so we should probably add it and return the error.

**Comment by andrewxhill** [comment]
related https://github.com/textileio/go-threads/issues/234

**Comment by carsonfarmer** [comment]
It was discussed at our recent team offsite that we might be able to  fix this (and that other issue) entirely by _not_ requiring the stop to be started first (i.e., auto-start the store or something similar)?

**Comment by sanderpick** [comment]
Yep, closing in favor of the auto-start issue.
