### ISSUE TITLE
Chat example seems broken

### ISSUE THREAD

**Issue by abour** [textileio/go-threads#170]
I got an error while testing the chat example. Test case:

1) Start the fist instance "i1"
2) Start the second instance "i2"
3) On "i1" run ":address"
4) On "i2" run ":add test"
5) On "i2" run ":enter test"
6) On "i2" run ":add-follower i1-address"
=> Error here.

When the "EventFromRecord" method is called, the block type is invalid.
```
  func EventFromRecord(ctx context.Context, dag format.DAGService, rec thread.Record) (*Event, error) {
	block, err := rec.GetBlock(ctx, dag)
	if err != nil {
		return nil, err
	}

	fmt.Printf("Type: %T", block) // Added for debug purpose. *cbornode.Node is printed

	event, ok := block.(*Event)
	if !ok {
		return nil, fmt.Errorf("invalid event")
	}
	return event, nil
  }
```

For debug purpose, I added the following line to test the type 
`fmt.Printf("Type: %T", block)
`
which returns `*cbornode.Node` while `block.(*Event)` was expected.
Maybe the method "EventFromNode" should be used instead of "EventFromRecord" ?

**Comment by sanderpick** [comment]
Hey @abour, thanks for the report. I'll take a look tomorrow.

**Comment by sanderpick** [comment]
@abour, here's a fix: https://github.com/textileio/go-threads/pull/178
