### ISSUE TITLE
Implement thread delete

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-threads#176]
Funny enough, this is still `panic("implement me")` :)

**Comment by carsonfarmer** [comment]
What is required here beyond purging thread information locally @sanderpick? Do we need to notify peers? Probably not right?

**Comment by sanderpick** [comment]
Off the top of the head,
- Update local addresses for _your_ log, i.e., delete them all
- Notify peers of the new addresses
- Walk the thread records, removing them from the block store
- Delete the log keys 
- Delete the thread keys
