### ISSUE TITLE
JSONMode: ModelFind can take single instance

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-threads#188]
Having to supply a slice as `inerface{}` bit me once. As pointed out by @jsign, that's not very intuitive. We should be able to use reflect and create a slice from the resolved type.

**Comment by asutula** [comment]
Yea both options seem pretty unintuitive to me. My thinking was to pass in the same type you get out (a slice). Otherwise, there is this inconsistency that has to be explained. But whatever, I get it either way and am fine with this change.

**Comment by jsign** [comment]
What about supporting both, and let reflect do the necessary to support both cases and behave appropriately.

**Comment by asutula** [comment]
Sounds like a great idea.

**Comment by sanderpick** [comment]
+1
