### ISSUE TITLE
error: too many open files

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-threads#189]
if i run the test suite in js client enough times back to back, i can get this pretty frequently, 

```
2019/12/31 15:29:49 http: Accept error: accept tcp 127.0.0.1:7006: accept: too many open files; retrying in 5ms
```

if i then wait a few seconds, it does accept a few more requests but then will throw that error again. maybe something to do with local machine settings / limits? if so, could a fix be included in the readme?

**Comment by sanderpick** [comment]
Yep, I was hitting the same thing running `textile` tests locally... I believe macos default settings make it tough to really hammer with a bunch of net requests.
