### ISSUE TITLE
Support use cases where a peer can write a log to a thread, but is unable to read

### ISSUE THREAD

**Issue by novocodev** [textileio/go-threads#220]
On resource constrained devices e.g. IoT where sensor data is being generated, it would be desirable to configure a peer to write to a log in a thread but be unable to read other logs.

This was briefly discussed on Slack, the following comment is from @sanderpick 

`Hmm, sounds like a useful thing to support. Not currently possible as @carsonfarmer says. Would you mind creating an issue on go-threads? We could discuss further there. Maybe we can make a way to join a thread that just says, “don’t download other logs and ignore others’ writes”. The downside is that you won’t materialize the same state, so part of this solution could be a new event codec that does not allow updates, only model creates… this would be like an IOT device kinda thing`

**Comment by novocodev** [comment]
Network I/O and network interface up time should also be considered a constrained resource in this use case.

Solutions that reduce data being sent by a constrained peer would be preferable to solutions that still send data to a constrained peer which then drops the data once received.

**Comment by sanderpick** [comment]
Hey @novocodev - Have you thought about using the raw threads layer for this? In an OIT settings, I don't think you'd need mutable database entries like the top level API provides. Just inserting raw records should be sufficient. In which case, we'd still need a way to signal that the edge nodes don't care about downloading others' logs.

**Comment by sanderpick** [comment]
Closing this as stale.
