### ISSUE TITLE
Build indexes if they don’t exist yet

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-threads#226]
Currently, calling AddIndex on a Model will only specify to use an index, it won't actually _build_ up the index on existing fields if they haven't already been indexed. It might be useful to ensure and index is up to date by building it up post-insertion after the fact.

From @sanderpick 
> mongodb has a nice pattern here: Let the dev run a function like, ensureIndexes or similar that applies index additions / changes.

**Comment by sanderpick** [comment]
Closing as superseded by https://github.com/textileio/go-threads/issues/286
