### ISSUE TITLE
Auto-start stores at creation time

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-threads#230]
Curious, wouldn’t it be nicer if a thread store just started itself after creation? I know we’ve stretched the capabilities of a store beyond it’s original use-case (multi-store, multi-tenant, etc.), but given it’s current trajectory, ideally a remote user wouldn’t have to “start” a store after registering models. They would just register them whenever needed without thinking much about it.

So, we’d have NewStore and NewStoreFromAddr instead of NewStore, Start, and StartFromAddr.

This would also make https://github.com/textileio/go-threads/issues/115 go away.

**Comment by sanderpick** [comment]
Thought, @jsign?

**Comment by jsign** [comment]
> Thoughts, @jsign?

As chatted out-of-band: the reason behind the `Start()` method is handling the case of a user joining an existing store. Doing an immediate _Start_ on _New_ may not leave room to do proper Model registering. Simplest solution to this is accepting a list of models in the _New_ param.

**Comment by burdiyan** [comment]
I think that would improve UX a lot! Starting things before using them is very error-prone IMHO. And it's also confusing when you have to close. I'd say that in Go it's common that you either don't have to close, and start passing a context, or you the thing starts during the initialization, and then you close in a deferred statement.
