### ISSUE TITLE
Why core/service is an interface?

### ISSUE THREAD

**Issue by burdiyan** [textileio/go-threads#247]
Glancing at the code, I started to wonder, why `core/service` is an interface? Is there any other implementation apart from the one in the `service` package? It seems to me that the core logic of a thread service mostly stays the same, but the underlying component could change (like data stores, DAGService and so on.

Am I missing something?

P.S. Not sure if this type of questions should be raised on Slack vs. GitHub. GitHub seems nicer as it's closer to the actual code, and history remains.

**Comment by sanderpick** [comment]
There is gRPC Go client that implements the same interface: https://github.com/textileio/go-threads/blob/master/service/api/client/client.go. Currently, this is used mostly to test the service and as a reference for other languages, like this JS one: ﻿﻿https://github.com/textileio/js-threads/blob/master/packages/service-client/src/index.ts#L82

Regarding where questions should go... here is fine!

**Comment by burdiyan** [comment]
Got it! Sounds reasonable.

Although I would prefer if `service.NewService` would export a concrete type instead of `core.Service`, it is probably a matter of personal preferences.
