### ISSUE TITLE
CreateRecords waits for push requests to be finished

### ISSUE THREAD

**Issue by requilence** [textileio/go-threads#309]
Here at `pushRecord`, you are waiting for all record push requests to the log addresses  to be done:
https://github.com/textileio/go-threads/blob/e1b3ffe98cb4c525c3ce3de99a4ba26f9e926223/net/client.go#L390

It can take a while when you have replicators for your log. For me it looks like CreateRecord execution time shouldn't depend on the number of addresses and their response time. 

And because it doesn't pass and return any error from the actual push request it looks like it waitgroup may be removed without any bad effects.

**Comment by sanderpick** [comment]
Hmm, I can't think of any reason why the wait is happening either. Looking...

**Comment by sanderpick** [comment]
Thanks for the tip, @requilence - change merged to master.
