### ISSUE TITLE
libp2p peerstore now in-memory

### ISSUE THREAD

**Issue by requilence** [textileio/go-threads#326]
After #324 by @jsign was merged, now go-threads will rely on the default libp2p peerstore, which is in-memory: https://github.com/libp2p/go-libp2p/blob/master/defaults.go#L48

But it looks like you assume that it is permanents: https://github.com/textileio/go-threads/blob/master/net/net.go#L528

Also, in-memory peerstore may be especially painful for mobile clients, which can be unloaded pretty often and will need to do discovery again and again

**Comment by jsign** [comment]
I think I got the sensation of being persistent since in the new version it requires a datastore, which isn't the case. I'll PR this change in a min.
Thanks @requilence !
