### ISSUE TITLE
threadsd crashes when attempting to add db by client.newDBFromAddr()

### ISSUE THREAD

**Issue by cchrs** [textileio/go-threads#342]
I'm trying to access a db by daemon 2 which was created by a different threads daemon 1. I first get the dbinfos by 

`dbInfo = await client.getDBInfo(dbID);`

from the threads daemon 1. Then I switch to the other daemon 2 and try to call 

`await client.newDBFromAddr(dbInfo.address[0], dbInfo.key, collections: [newCollection]);`

And get the dart error: 

> Unhandled exception:
> gRPC Error (2, failed to dial 12D3KooWJEwjTgJUfvwSeoW7TcqTHDevnBM1huyPY9jZcj1sccag: no good addresses)

What am I doing wrong?

When I then run again:

`await client.newDBFromAddr(dbInfo.address[0], dbInfo.key, collections: [newCollection]);`

results in error:

> Unhandled exception:
> gRPC Error (2, thread already exists)

If I then try to access the DB still from daemon 2 with

`await client.getDBInfo(dbID);`

The daemon crashes with 

> 2020-05-09T14:25:42.328+0200	DEBUG	net	net/net.go:360	pulling thread bafkzjg7rdddl73kg4cq7iszrnyajs22ipbamersunjqkav52ajs36qq...
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x17b7a49]
> 
> goroutine 38893 [running]:
> github.com/textileio/go-threads/db.(*DB).GetDBInfo(0x0, 0xc00427db28, 0x1, 0x1, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	/home/runner/work/go-threads/go-threads/db/db.go:298 +0x99
> github.com/textileio/go-threads/api.(*Service).GetDBInfo(0xc001fa6d70, 0x1f81240, 0xc0085835f0, 0xc0086a59c0, 0xc001fa6d70, 0xc0085835f0, 0xc007f87ba0)
> 	/home/runner/work/go-threads/go-threads/api/service.go:232 +0x275
> github.com/textileio/go-threads/api/pb._API_GetDBInfo_Handler(0x1c8c880, 0xc001fa6d70, 0x1f81240, 0xc0085835f0, 0xc0040e2d20, 0x0, 0x1f81240, 0xc0085835f0, 0xc008118870, 0x24)
> 	/home/runner/work/go-threads/go-threads/api/pb/api.pb.go:2506 +0x217
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc001fc8340, 0x1f8ce00, 0xc008f0b500, 0xc006ec8c00, 0xc00365a180, 0x280ff70, 0x0, 0x0, 0x0)
> 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.0/server.go:1082 +0x50a
> google.golang.org/grpc.(*Server).handleStream(0xc001fc8340, 0x1f8ce00, 0xc008f0b500, 0xc006ec8c00, 0x0)
> 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.0/server.go:1405 +0xccb
> google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc008744050, 0xc001fc8340, 0x1f8ce00, 0xc008f0b500, 0xc006ec8c00)
> 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.0/server.go:746 +0xa1
> created by google.golang.org/grpc.(*Server).serveStreams.func1
> 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.0/server.go:744 +0xa1

and dart error:

> Unhandled exception:
> gRPC Error (2, HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10))

**Comment by carsonfarmer** [comment]
Our dart clients are no longer supported to the same degree that our Javascript and Go ones are. Having said that, I suspect the issue here is that the first address in that address array is a localhost address, so it is not dialble. Are you running this on the same machine? Same network?

**Comment by sanderpick** [comment]
Closing as stale.
