### ISSUE TITLE
go get: no Go files in directory

### ISSUE THREAD

**Issue by ShishKabab** [textileio/go-threads#371]
I'm trying to install the local Go daemon, but get an error:
```
$ go get github.com/textileio/go-threads
package github.com/textileio/go-threads: no Go files in /home/vincent/go/src/github.com/textileio/go-threads
$ go get github.com/textileio/go-threads
can't load package: package github.com/textileio/go-threads: no Go files in /home/vincent/go/src/github.com/textileio/go-threads
```

This is preventing me from getting started with ThreadsDB  :(

**Comment by andrewxhill** [comment]
you can install the go daemon with

```
go install threadsd/main.go 
```

if you are looking for the correct `go get` steps in particular, you can do

```
go get ./...
```

**Comment by sanderpick** [comment]
Sounds like you're trying to import threads as a library into your own project. In that case, are you in a go module project? 

```
mkdir myproj && cd myproj
go mod init github.com/.../myproj
go get -u github.com/textileio/go-threads
```

**Comment by sanderpick** [comment]
Oops, I need more coffee :) You're looking for the daemon. If you want to install from source, do what I mentioned above and then,

```
go install ./...
```
That will put the daemon in your `GOPATH/bin` folder, which should be in your `PATH`.

Or download a release -> https://github.com/textileio/go-threads/releases

**Comment by ShishKabab** [comment]
Ahhh, overlooked the releases! Ended up with the `go get` command through the docs. [here](https://docs.textile.io/threads/#developer-api) I saw:
```
By default, a ThreadDB will connect with a local go-threads Threads Daemon. See the go-threads for details on getting started with local development.
```

and then I ended up on the GitHub page where the `Install` section mentioned `go get`. Only now re-reading it, I see the releases mentioned at the end of the same paragraph  :)

**Comment by carsonfarmer** [comment]
Closing this as the docs have been updated, hopefully leading to less confusion around building from source.
