### ISSUE TITLE
cannot find package /extra25519

### ISSUE THREAD

**Issue by chenak-a** [textileio/go-threads#383]
![image](https://user-images.githubusercontent.com/66174511/85836429-943f2400-b764-11ea-9e50-8650d5cbd583.png)
 this is the issue : https://github.com/agl/ed25519/issues/27
mb the solution : https://godoc.org/golang.org/x/crypto/ed25519 this dont work.
you can swap agl with decred : extra "github.com/decred/ed25519/extra25519"

![image](https://user-images.githubusercontent.com/66174511/85850040-079f6080-b77a-11ea-9d43-e11f17056b4f.png)
after the fix

**Comment by chenak-a** [comment]
now i have an other issue:
![image](https://user-images.githubusercontent.com/66174511/85845909-03bc1000-b773-11ea-98a5-36b69c022944.png)

**Comment by chenak-a** [comment]
![image](https://user-images.githubusercontent.com/66174511/85850040-079f6080-b77a-11ea-9d43-e11f17056b4f.png)

**Comment by jsign** [comment]
Hey @chenak-a , thanks a lot for raising this issue.

Taking a more detailed look, we use `agl/ed25519` for a public/private point conversion between elliptic curves Curve25519/Ed25519, mostly for using the same private key for signature and encryption using NaCl.

[This](https://github.com/golang/go/issues/20504) issue is tracking including this conversion, which would be the nicest way to solve this. In the meantime, I _seems_ we can consider [the `age` implementation](https://github.com/FiloSottile/age/blob/bbab440e198a4d67ba78591176c7853e62d29e04/internal/age/ssh.go#L174) of this conversions. `age` is done by Fillipo Valsorda which is most probably the best person to rely on for Go crypto.

Apart from doing the change, we should add some tests between the old and new implementations to really check things.

**Comment by carsonfarmer** [comment]
Good call on the age implementation, I would agree with your assessment here @jsign. Not that it matters _too_ much, but our JS libs for crypto _also_ mongomery/edwards key conversion. This issue https://github.com/golang/go/issues/20504 also appears to suggest age (among other solutions).
