### ISSUE TITLE
Does it supports database sharding? 

### ISSUE THREAD

**Issue by bitcard** [textileio/go-threads#391]
If database is ver big, does It support sharding data to many maching?
If support, how to config replication factor?

what's different from orbit-db?

thanks.

**Comment by sanderpick** [comment]
Hey @bitcard, no sharding at this point. 

There's a lot of difference to orbitdb. Is there some feature you're curious about? The list of items in the [readme table](https://github.com/textileio/go-threads#whats-new) describes some of the high level features of threads.

**Comment by bitcard** [comment]
> Hey @bitcard, no sharding at this point.
> 
> There's a lot of difference to orbitdb. Is there some feature you're curious about? The list of items in the [readme table](https://github.com/textileio/go-threads#whats-new) describes some of the high level features of threads.

thank you for your reply. if no sharding, how to scale up applicaiton? does it support replicaiton factor like ipfs cluster?

**Comment by carsonfarmer** [comment]
Hi @bitcard, thanks for your questions. You'll likely get faster responses and and a more complete answer if you use our Slack channel for these types of queries: https://slack.textile.io. We like to keep GitHub "Issues" for specific issues and bugs/feature requests.
