### ISSUE TITLE
Should there be a `GetTokenChallenge` method for `Client`?

### ISSUE THREAD

**Issue by samikshan** [textileio/go-threads#395]
You can `getTokenChallenge` using js-threads on server-side, to get a challenge that can be sent back to the client for signing, and eventual verification of user identity. If you are running Go on your server, you'd probably need to have a similar flow. Right now we have a `GetToken()` method for threads client, that gets a token challenge, signs the challenge using the identity, and submits the signed challenge to get back the token.

Would it make sense instead to take out the getting the challenge bits from `GetToken` and putting it in a separate method, `GetTokenChallenge`, that would enable a workflow similar to what is possible through js-threads? If yes, I would like to work on a quick PR.

**Comment by sanderpick** [comment]
Hey @samikshan, it's probably useful if you're running into this question, though I'm not totally clear on the use case. The challenge you get from this standalone method `GetTokenChallenge`, what would the caller do with that?

**Comment by samikshan** [comment]
@sanderpick Hey. Sure, let me elaborate a bit on the use case which is basically a try at implementing authentication in my app as explained in the documentation: https://docs.textile.io/tutorials/hub/production-auth/. The difference is that I am trying to use Go (Echo framework) for the server. So,
1. The client, creates an identity (a key pair)
2. The client sends a token request to the server (with the public key)
3. The (Go) server requests for a challenge for the new token request and sends the challenge via websocket back to the client (this is where it would probably help to have a `GetTokenChallenge()` method?)
4. The client signs the challenge and responds back to the server.
5. The server verifies the signed challenge and responds back with the auth tokens to the client to complete the authentication.

**Comment by sanderpick** [comment]
Ah, okay that helps. Why not just have your client directly get a token from the threads server (threadd / hubb / buckd)?

**Comment by samikshan** [comment]
Yeah exactly. I have taken that approach and am considering an entirely serverless design for my application. But for cases as described above, where the server (implemented in Go) would need to verify and store the public keys of users, this method would probably help.

**Comment by sanderpick** [comment]
Sorry for the delay here! Okay, that makes sense. I'm all for having as much flex as possible.

**Comment by sanderpick** [comment]
Closing as stale, feel free to reopen if you still need this / are working on it.
