### ISSUE TITLE
dispatcher broken for old-style event with time.Time

### ISSUE THREAD

**Issue by requilence** [textileio/go-threads#443]
I've just tested https://github.com/textileio/go-threads/pull/439 and got the gob encode error in the dispatcher for old-format event [here](https://github.com/textileio/go-threads/blob/master/db/dispatcher.go#L80)
```gob: type not registered for interface: map[string]interface {}```

So looks like an empty time.Time decoded into map[string]interface which is not auto-registred in the gob

**Comment by sanderpick** [comment]
Does registering `time.Time` with gob help?

**Comment by requilence** [comment]
@sanderpick cbor encodes time.Time as empty map, not a struct, so it works with `gob.Register(map[string]interface {}{})`
I made the PR: #444
