### ISSUE TITLE
Sort is applied after limit and skip

### ISSUE THREAD

**Issue by deefactorial** [textileio/go-threads#452]
If I query instances with a `sort` on it, with a `limit` and `skip` the sort is applied after the `limit` and `skip`. I expected the `sort` to be applied before the `limit` and `skip`.

Set of steps to reproduce the issue:
Create Thread > Create Collection > Insert 20 ordered items into collection > Query Instances with `sort` `limit` and `skip` 

Expected Behavior:
When you query items `sort` should be applied before the `limit` and `skip` so you can paginate through the results

**Comment by carsonfarmer** [comment]
Fixed with #478. This should be in the next go-threads release, which means it will automatically be in js-threads-clients running against the next threads daemon release.
