### ISSUE TITLE
Trouble Saving JSON Strings w/ Validation

### ISSUE THREAD

**Issue by JamieRez** [textileio/go-threads#453]
Hi Textile, I'm building a live chat app via threads, which has to have write validation for most of the collections.

I notice an error being thrown when I try to create an instance with a JSON string, in this case I am saving a stringified dbInfo object to a created contact instance. 

Here's the writeValidatorStr I pass to my contacts collection. Only the owner of the thread should be able to write over their contacts list.

```
const writeValidatorStr = `let ownerPub = '${this.identity.public.toString()}';
if (writer === ownerPub) {
  return true;
}
return false;
`;  
```

Here's an example of the data I'm saving and the error I get in the console

<img width="465" alt="Screen Shot 2020-10-08 at 11 14 30 AM" src="https://user-images.githubusercontent.com/10690898/96755196-4095bd80-1387-11eb-93d0-b7d73e36dfab.png">

This blocks the instance from being created if I have writeValidation setup. 

Could this somehow be a parsing error on the backend where the validation function runs?

**Comment by deefactorial** [comment]
Looks like you need to escape the double quotes in the string otherwise it thinks it's the end of the string. Hence the error about the invalid character 'k'.
ex: `dbInfo: "{"key"...` would be like so `dbInfo: "{\"key\":...`

**Comment by carsonfarmer** [comment]
The above explanation is correct. Additionally, I believe @JamieRez got this working previously.
