### ISSUE TITLE
--- FAIL: TestModifiedSince (0.00s)

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-threads#520]
```
--- FAIL: TestModifiedSince (0.00s)
    --- FAIL: TestModifiedSince/WithCreateSaveAndDelete (1.17s)
Error:         collection_test.go:956: should have modfied id 01f6qja077rszyvjp9tw4rw817
```

This failure happen intermittently. I remember this from ages ago... not sure if we introduced a regression somehow. cc @carsonfarmer can you take a look at this?

**Comment by carsonfarmer** [comment]
Taking a look now. Looks like a naive test that I can PR a fix for lickety split!
