### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by omar391** [textileio/go-threads#587]
Hi,

I am using this project in one of my production apps. But I have some concerns about the commit gap being long since the last commit. Also many projects in "textileio" is being achieved.

Could please confirm the future plan for this project? cc @sanderpick 

Best.

**Comment by sanderpick** [comment]
Hey @omar391, thanks for the issue. We aren't actively developing threads anymore, but the org is still here and building other things. We're happy to field any questions you have. Cheers!
