### ISSUE TITLE
Store API (gRPC)

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-threads#59]
We'll need a daemon that runs a server and a gRPC service that can control multiple stores.

### RPC Methods
- [x] `NewStore`
- [x] `RegisterSchema`
- [x] `Start`
- [x] `StartFromAddress`
- [x] `ModelCreate`
- [x] `ModelHas`
- [x] `ModelSave`
- [x] `ModelDelete`
- [x] `ModelReadTxn`
- [x] `ModelWriteTxn`
- [x] `ModelFindByID`
- [x] `ListenForStateChanges`?
- [ ] others?

**Comment by asutula** [comment]
Added some additional methods to the list above
