### ISSUE TITLE
Proxy Log Manager

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-threads#63]
Daemon based, manage multiple logs per thread

- [ ] https://github.com/textileio/go-textile-threads/issues/54 JWTs used to enable remote log writing
- [ ] https://github.com/textileio/go-textile-threads/issues/55 Serve and push over a web-socket at the thread level

**Comment by sanderpick** [comment]
I have this in other issues

**Comment by andrewxhill** [comment]
i just need something the public can follow
